version: yml.{build}
clone_depth: 5
build_script:
   - cmd: 'mkdir out\classes'
   - cmd: 'dir /S /B /A:-D src >out\classes.list'
   - cmd: 'javac -Xlint:deprecation -Xlint:unchecked -d "out\classes" -sourcepath "src" -cp "json-simple\json-simple-1.1.1.jar;lwjgl-2.9.0\jar\lwjgl.jar;lwjgl-2.9.0\jar\slick-util.jar" @out\classes.list'

   - cmd: 'XCOPY out\classes out\client_cp /S /I /Q'
   - cmd: '"C:\Program Files\7-Zip\7z.exe" x -oout\client_cp -r -y json-simple\json-simple-1.1.1.jar'
   - cmd: '"C:\Program Files\7-Zip\7z.exe" x -oout\client_cp -r -y lwjgl-2.9.0\jar\lwjgl.jar'
   - cmd: '"C:\Program Files\7-Zip\7z.exe" x -oout\client_cp -r -y lwjgl-2.9.0\jar\slick-util.jar'
   - cmd: '"C:\Program Files\7-Zip\7z.exe" x -oout\client_cp -r -y lwjgl-2.9.0\jar\jarsplice-0.40.jar'
   - cmd: 'rm out\client_cp\META-INF\MANIFEST.MF'
   - cmd: 'XCOPY levels out\client_cp\levels /S /I /Q'
   - cmd: 'XCOPY res out\client_cp\res /S /I /Q'
   - cmd: 'XCOPY shaders out\client_cp\shaders /S /I /Q'
   - cmd: 'XCOPY lwjgl-2.9.0\native\windows out\client_cp /S /I /Q'
   - cmd: 'XCOPY lwjgl-2.9.0\native\macosx out\client_cp /S /I /Q'
   - cmd: 'XCOPY lwjgl-2.9.0\native\linux out\client_cp /S /I /Q'
   - cmd: 'ECHO Manifest-Version: 1.0>out\client-manifest.mf'
   - cmd: 'ECHO Launcher-Main-Class: net.fe.FEMultiplayer>>out\client-manifest.mf'
   - cmd: 'ECHO Launcher-VM-Args: >>out\client-manifest.mf'
   - cmd: 'ECHO Main-Class: org.ninjacave.jarsplice.JarSpliceLauncher>>out\client-manifest.mf'
   - cmd: 'ECHO Class-Path: .>>out\client-manifest.mf'
   - cmd: 'jar cfm "out\FEMP-client.jar" "out\client-manifest.mf" -C out\client_cp .'

   - cmd: 'ECHO .wav>out\server-res-exclude.txt'
   - cmd: 'ECHO .png>>out\server-res-exclude.txt'
   - cmd: 'XCOPY out\classes out\server_cp /S /I /Q'
   - cmd: '"C:\Program Files\7-Zip\7z.exe" x -oout\server_cp -r -y json-simple\json-simple-1.1.1.jar'
   - cmd: '"C:\Program Files\7-Zip\7z.exe" x -oout\server_cp -r -y lwjgl-2.9.0\jar\lwjgl.jar'
   - cmd: '"C:\Program Files\7-Zip\7z.exe" x -oout\server_cp -r -y lwjgl-2.9.0\jar\slick-util.jar'
   - cmd: 'rm out\server_cp\META-INF\MANIFEST.MF'
   - cmd: 'XCOPY levels out\server_cp\levels /S /I /Q'
   - cmd: 'XCOPY res out\server_cp\res /S /I /Q /EXCLUDE:out\server-res-exclude.txt'
   - cmd: 'jar cfe "out\FEMP-server.jar" "net.fe.network.FEServer" -C out\server_cp .'

   - cmd: 'ECHO .wav>out\mapping-res-exclude.txt'
   - cmd: 'ECHO \battle_anim\>>out\mapping-res-exclude.txt'
   - cmd: 'ECHO \map_anim\>>out\mapping-res-exclude.txt'
   - cmd: 'ECHO \gui\>>out\mapping-res-exclude.txt'
   - cmd: 'ECHO \map_mugshots\>>out\mapping-res-exclude.txt'
   - cmd: 'ECHO \palette\>>out\mapping-res-exclude.txt'
   - cmd: 'XCOPY out\classes out\mapping_cp /S /I /Q'
   - cmd: '"C:\Program Files\7-Zip\7z.exe" x -oout\mapping_cp -r -y json-simple\json-simple-1.1.1.jar'
   - cmd: '"C:\Program Files\7-Zip\7z.exe" x -oout\mapping_cp -r -y lwjgl-2.9.0\jar\lwjgl.jar'
   - cmd: '"C:\Program Files\7-Zip\7z.exe" x -oout\mapping_cp -r -y lwjgl-2.9.0\jar\slick-util.jar'
   - cmd: '"C:\Program Files\7-Zip\7z.exe" x -oout\mapping_cp -r -y lwjgl-2.9.0\jar\jarsplice-0.40.jar'
   - cmd: 'rm out\mapping_cp\META-INF\MANIFEST.MF'
   - cmd: 'XCOPY res out\mapping_cp\res /S /I /Q /EXCLUDE:out\mapping-res-exclude.txt'
   - cmd: 'XCOPY shaders out\mapping_cp\shaders /S /I /Q'
   - cmd: 'XCOPY lwjgl-2.9.0\native\windows out\mapping_cp /S /I /Q'
   - cmd: 'XCOPY lwjgl-2.9.0\native\macosx out\mapping_cp /S /I /Q'
   - cmd: 'XCOPY lwjgl-2.9.0\native\linux out\mapping_cp /S /I /Q'
   - cmd: 'ECHO Manifest-Version: 1.0>out\mapping-manifest.mf'
   - cmd: 'ECHO Launcher-Main-Class: net.fe.editor.LevelEditor>>out\mapping-manifest.mf'
   - cmd: 'ECHO Launcher-VM-Args: >>out\mapping-manifest.mf'
   - cmd: 'ECHO Main-Class: org.ninjacave.jarsplice.JarSpliceLauncher>>out\mapping-manifest.mf'
   - cmd: 'ECHO Class-Path: .>>out\mapping-manifest.mf'
   - cmd: 'jar cfm "out\FEMP-mapping.jar" "out\mapping-manifest.mf" -C out\mapping_cp .'
test_script:
   - cmd: 'mkdir out\test_lib'
   - cmd: 'curl -sS -o out\test_lib\junit-platform-console-standalone-1.2.0.jar https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.2.0/junit-platform-console-standalone-1.2.0.jar'

   - cmd: 'mkdir out\test_classes'
   - cmd: 'dir /S /B /A:-D test >out\test_classes.list'
   - cmd: 'javac -Xlint:deprecation -Xlint:unchecked -d "out\test_classes" -cp "out\test_lib\junit-platform-console-standalone-1.2.0.jar;out\classes;json-simple\json-simple-1.1.1.jar;lwjgl-2.9.0\jar\lwjgl.jar;lwjgl-2.9.0\jar\slick-util.jar" @out\test_classes.list'
   - cmd: 'java -jar out\test_lib\junit-platform-console-standalone-1.2.0.jar --reports-dir "out\test_reports" --classpath ".;out\test_classes;out\classes;json-simple\json-simple-1.1.1.jar;lwjgl-2.9.0\jar\lwjgl.jar;lwjgl-2.9.0\jar\slick-util.jar" -p net.fe'

   - ps: '$wc = New-Object System.Net.WebClient'
   - ps: '$wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\out\test_reports\TEST-junit-vintage.xml))'
artifacts:
- path: out\*.jar
